In [1]:
import numpy as np

In [2]:
arr = np.arange(11)

In [3]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
np.sqrt(arr)

array([ 0.        ,  1.        ,  1.41421356,  1.73205081,  2.        ,
        2.23606798,  2.44948974,  2.64575131,  2.82842712,  3.        ,
        3.16227766])

In [5]:
np.exp(arr)

array([  1.00000000e+00,   2.71828183e+00,   7.38905610e+00,
         2.00855369e+01,   5.45981500e+01,   1.48413159e+02,
         4.03428793e+02,   1.09663316e+03,   2.98095799e+03,
         8.10308393e+03,   2.20264658e+04])

In [6]:
A = np.random.randn(10)

In [7]:
A

array([-0.58767158,  1.72085345, -1.50196289,  1.0117647 ,  0.12059627,
       -1.09934504,  0.34504538,  1.21722994,  1.9583323 ,  0.41034723])

In [8]:
B = np.random.randn(10)

In [9]:
B

array([-2.00251212,  1.02601078, -0.48997347,  0.65339202,  0.66679075,
       -0.18099657, -0.41097683,  1.46780069, -0.54419437, -2.01980688])

In [11]:
np.add(A,B)

array([-2.5901837 ,  2.74686423, -1.99193635,  1.66515672,  0.78738702,
       -1.28034161, -0.06593145,  2.68503063,  1.41413794, -1.60945965])

np.maximum(A,